import google.generativeai as genai
import os
import dotenv
import json
from django.conf import settings

# Load environment variables from .env file
dotenv.load_dotenv()


def generate_ai_content(presentation_title: str, slide_titles):
    # Retrieve the API key from the environment variable
    api_key = os.getenv("GEMINI_API")
    if not api_key:
        raise ValueError("GEMINI_API environment variable is not set.")

    # Configure the API with the provided key
    genai.configure(api_key=api_key)

    # Instantiate the model (ensure "gemini-1.5-flash" is valid)
    model = genai.GenerativeModel("gemini-1.5-flash")

    try:
        # Get the absolute path for the prompt.txt file
        prompt_file_path = os.path.join(settings.BASE_DIR, "ai", "prompt.txt")

        # Read the prompt from the txt file
        with open(prompt_file_path, "r") as file:
            slide_prompt = file.read()

        # Format the slide prompt with the provided topic
        slide_prompt = slide_prompt.replace("{presentation_title}", presentation_title)
        slide_prompt = slide_prompt.replace("{slide_titles}", str(slide_titles))
        # print(slide_prompt)

        # Send the slide generation request to the model
        response = model.generate_content(slide_prompt)

        # Check if the response contains text
        if response and hasattr(response, "text"):
            content = response.text
            content = content.replace("```json", "").replace("```", "").strip()
            return content
        else:
            return "Error: No content generated."

    except Exception as e:
        # Return the error message in case of any issues
        return f"Error during API request: {e}"


def generate_ai_content_slide(prompt: str, project_title: str):
    # Retrieve the API key from the environment variable
    api_key = os.getenv("GEMINI_API")
    if not api_key:
        raise ValueError("GEMINI_API environment variable is not set.")

    # Configure the API with the provided key
    genai.configure(api_key=api_key)

    # Instantiate the model
    model = genai.GenerativeModel("gemini-1.5-flash")

    try:
        # Get the absolute path for the prompt.txt file
        prompt_file_path = os.path.join(settings.BASE_DIR, "ai", "add_slide_prompt.txt")

        # Read the prompt template from the file
        with open(prompt_file_path, "r") as file:
            slide_prompt = file.read()

        # Format the slide prompt with the provided topic and presentation title
        slide_prompt = slide_prompt.replace("{prompt}", prompt)
        slide_prompt = slide_prompt.replace("{presentation_title}", project_title)

        # Send the slide generation request to the model
        response = model.generate_content(slide_prompt)

        # Parse the response and extract JSON content from the AI output
        if response and hasattr(response, "candidates") and response.candidates:
            ai_content = response.candidates[0].content.parts[0].text

            # Clean up the response to extract valid JSON
            ai_content = ai_content.replace("```json", "").replace("```", "").strip()

            # Parse and return the JSON content
            try:
                slide_data = json.loads(ai_content)
                return slide_data
            except json.JSONDecodeError as e:
                return {"error": f"Failed to parse AI response: {str(e)}"}

        else:
            return {"error": "No content generated by the AI model."}

    except Exception as e:
        # Return the error message in case of any issues
        return {"error": f"Error during API request: {str(e)}"}


def generate_ai_title_slide(project_title: str, existing_titles):
    # Retrieve the API key from the environment variable
    api_key = os.getenv("GEMINI_API")
    if not api_key:
        raise ValueError("GEMINI_API environment variable is not set.")

    genai.configure(api_key=api_key)

    # Instantiate the model (ensure "gemini-1.5-flash" is valid)
    model = genai.GenerativeModel("gemini-1.5-flash")

    try:
        # Get the absolute path for the prompt.txt file
        prompt_file_path = os.path.join(
            settings.BASE_DIR, "ai", "title_slide_prompt.txt"
        )

        # Read the prompt from the txt file
        with open(prompt_file_path, "r") as file:
            slide_prompt = file.read()
        existing_titles_str = json.dumps(existing_titles)
        slide_prompt = slide_prompt.replace("{presentation_title}", project_title)
        slide_prompt = slide_prompt.replace("{existing_titles}", existing_titles_str)

        # Send the slide generation request to the model
        response = model.generate_content(slide_prompt)

        # Check if the response contains text
        if response and hasattr(response, "text"):
            content = response.text
            content = content.replace("```json", "").replace("```", "").strip()
            return content
        else:
            return "Error: No content generated."

    except Exception as e:
        # Return the error message in case of any issues
        return f"Error during API request: {e}"


def generate_ai_outline(prompt: str, pages: int):
    # Retrieve the API key from the environment variable
    api_key = os.getenv("GEMINI_API")
    if not api_key:
        raise ValueError("GEMINI_API environment variable is not set.")

    genai.configure(api_key=api_key)

    # Instantiate the model (ensure "gemini-1.5-flash" is valid)
    model = genai.GenerativeModel("gemini-1.5-flash")

    try:
        # Get the absolute path for the prompt.txt file
        prompt_file_path = os.path.join(settings.BASE_DIR, "ai", "generate_outline.txt")

        # Read the prompt from the txt file
        with open(prompt_file_path, "r") as file:
            slide_prompt = file.read()
        slide_prompt = slide_prompt.replace("{presentation_prompt}", prompt)
        slide_prompt = slide_prompt.replace("{pages}", str(pages))

        # Send the slide generation request to the model
        response = model.generate_content(slide_prompt)

        # Check if the response contains text
        if response and hasattr(response, "text"):
            content = response.text
            content = content.replace("```json", "").replace("```", "").strip()
            return content
        else:
            return "Error: No content generated."

    except Exception as e:
        # Return the error message in case of any issues
        return f"Error during API request: {e}"
